prepare-local:
	yarn
	yarn add @react-navigation/native
	expo install react-native-screens react-native-safe-area-context
	yarn add react-native-screens react-native-safe-area-context
	expo install react-native-safe-area-context
	yarn add native-base styled-components styled-system
	expo install react-native-svg
	yarn add react-native-calendars